### ISSUE TITLE
Package doesn't work with TF 2.5.0

### ISSUE THREAD

**Issue by lminer** [yanivopo/Xvector#5]
If I try to install with TF 2.5.0 as specified in the current requirements.txt, I get a bunch of errors around clashing requirements. Moreover, the code doesn't appear to work with TF 2.5.0 as it still works with the graph object. The fix seems to be bumping the requirements back down, albeit with a small change to tensorflow-estimator:

```
audioread==2.1.6
h5py==2.9.0
Keras==2.2.4
librosa==0.6.3
matplotlib==3.0.3
numpy==1.16.3
pandas==0.24.2
PyAudio==0.2.11
pydub==0.23.1
requests==2.21.0
scikit-learn==0.21.1
scipy==1.2.1
six==1.12.0
SoundFile==0.10.2
tensorflow==1.15.4
tensorflow-estimator==1.15.1
tqdm==4.35.0
webrtcvad==2.0.10
```

**Comment by AvivSham** [comment]
Thank you for the heads up the current codebase is not aligned with TF 2.X versions (where keras is integrated into tf and tf using dynamic graph).
The tf version was downgraded to the previous version.
